### ISSUE TITLE
IOS :-scanning Error - BluetoothLE is in unknown state

### ISSUE THREAD

**Issue by Manish123Pandia** [Polidea/react-native-ble-plx#417] opened 2019-02-19 11:25 UTC
Here is my code : 

startDeviceScan(scanTimeout) {
		var me = this;
		// first destroy BLE manager object and re-initialize it 
		this.manager.destroy();
		this.manager = new BleManager();
		this.manager.startDeviceScan(null, null, (error, device) => {
			if (error) {
				// Handle error (scanning will be stopped automatically)
				console.log("scanning Error - " + error.message);
				me.startDeviceScan();
				return;
			}
			if (device)
				me.emit('startScanSuccess', device);
		});
	}

previously it was working fine for both IOS and Android but after using destroy() it is working fine on android but giving the error in case of IOS.

**Comment by Cierpliwy** [comment] 2019-02-19 11:30
Once a BLEManager instance is created, CBCentralManager is instantiated on iOS. For small period of time BLE stack is in Unknown state, after which it transitions to "PoweredOn" or other one. There is a function which allows you to monitor BLE state. Check code snippet [on introduction page](https://polidea.github.io/react-native-ble-plx/).

Closing as this behaviour is expected.

**Closed by Cierpliwy** 2019-02-19 11:30 UTC

**Comment by roysG** [comment] 2019-08-28 14:12
I get this message even when i wait 10 minutes!

'error blueee', [BleError: BluetoothLE is in unknown state]
[68047:2469569] 'error blueee', [BleError: BluetoothLE is in unknown state]

**Comment by NN01010101** [comment] 2019-09-21 12:51
@Cierpliwy @roysG, I can confirm, looks like the Unknown state is always the first response, no matter how long the app has been running. Once Unknown State error has been thrown, state changes to Powered On.

**Comment by ad-boschung** [comment] 2020-07-16 15:39
@NN01010101 You're right it's only an issue when the remote debugger is enabled.   
@Cierpliwy I don't understand why it is NOT documented. It would have earn me a lot of crucial time....

**Comment by danielfigueroaj** [comment] 2020-07-16 20:29
@ad-boschung how do you disable the remote debugger? is it something in xcode or react native?

**Comment by ad-boschung** [comment] 2020-07-17 06:15
It's a React Native feature. It's explained [here](https://reactnative.dev/docs/debugging).

**Comment by SunstroUS** [comment] 2020-08-05 16:50
I think remote debugging is off by default. At least on my build, when I shake my device, it is showing ' Debug ' as an option, meaning it hasn't started debugging yet. I have already tried turning that on, then off again to see if it would produce a different result. Not sure what is happening.

**Comment by EzeRangel** [comment] 2020-12-02 22:15
This also happen when you're using functional components and/or Hooks. Even if you disable the remote debug, still shows the Unknown state Error.

**Comment by JesusTectronic** [comment] 2022-12-05 23:00
var state = await bleManager.state()
while (state == State.Unknown) {
  delay(500)
  state = await bleManager.state()
}

**Comment by priyasamyal** [comment] 2024-01-03 12:41
Hi @ManishKumarPandia  Any update on this. As I am still facing the same issue. Already checked the device State as well
