### ISSUE TITLE
 BleGattException status=133

### ISSUE THREAD

**Issue by ethan6077** [Polidea/react-native-ble-plx#137] opened 2017-09-12 06:28 UTC
Hi,

I am testing the Sniffator on Samsung. This error happens frequently.
If I connect to the device two or three times, it would succeed.
The same code works fine on other phones like Apple and Pixel.
It only happens on Samsung, but Samsung is a really popular phone, I really want to solve that problem.
Has anyone got any idea on that?

Phone Name: Galaxy s6 edge
OS: Android 7.0
![screenshot_20170912-153816](https://user-images.githubusercontent.com/5506416/30311129-3c2047a4-97d7-11e7-8986-478462e05686.png)

**Comment by Cierpliwy** [comment] 2017-11-29 20:13
Duplicate of #50.

**Closed by Cierpliwy** 2017-11-29 20:13 UTC
