### ISSUE TITLE
onDeviceDisconnected doesn't detect lost connection to device

### ISSUE THREAD

**Issue by josef256** [Polidea/react-native-ble-plx#675] opened 2020-05-15 16:46 UTC
## Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

after connecting to device, i try to disable bluetooth or disconnect my device for example.
onDeviceDisconnected should intercept this behaviour and alert me wehenver im disconnected.
## Current Behavior
onDeviceDisconnected  is never fired
**this also apply to onDisconnected**
>   this.manager.onDeviceDisconnected(device.id, (error, device) => {
>               if (error) {
>                 console.log(error);
>               }
>               console.log('Device is disconnected');
>             });

the console log is never shown

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. connect to a device
2.  try to interrupt the connection(close bluetooth, disconnect your device..)
3. check if onDeviceDisconnected output something 

### Context

* Library version: 2.0.0
* Platform: Android.
* react native :0.62

here is what my function look like:
```js
 scanAndConnect() {
    this.manager.startDeviceScan(null, null, (error, device) => {
      if (error) {
        return;
      }
      if (device.id === '61:A9:15:96:3D:2C') {
        this.manager.stopDeviceScan();
        device
          .connect()
          .then(device => {
            this.manager.onDeviceDisconnected(device.id, (error, device) => {
              if (error) {
                console.log(error);
              }
              console.log('Device is disconnected');
            });
            return device.discoverAllServicesAndCharacteristics();
          })
          .then(device => {
            // Do work on device with services and characteristics
          })
          .catch(error => {
            console.log('errr ', error);
          });
        // Proceed with connection.
      }
    });
  }
```

**Comment by Barbiero** [comment] 2020-05-15 17:41
Possibly a duplicate of #663

**Closed** 2020-06-05 20:00 UTC
Labels: bug
