### ISSUE TITLE
hey how can i continously read data sent by a ble?

### ISSUE THREAD

**Issue by yangchange** [Polidea/react-native-ble-plx#463] opened 2019-05-13 13:47 UTC
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

Please describe the question.

**Comment by dariuszseweryn** [comment] 2019-05-13 13:51
Duplicate of #392

**Closed by dariuszseweryn** 2019-05-13 13:51 UTC
Labels: duplicate, question
